# Use a Node.js image
FROM node:14

# Set working directory
WORKDIR /app

# Copy client files
COPY . .

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
