# Use a Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy client files
COPY . .

# Install dependencies
RUN npm install --force

# Expose the port the app runs on
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
