# Use a Node.js image
FROM node:14

# Set working directory
WORKDIR /app

# Copy server files
COPY . .

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 5000

# Run the server
CMD ["node", "server.js"]
