# Use a Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy server files
COPY . .
rm -rf node_modules package-lock.json

# Install dependencies
RUN npm install --force

# Expose the port the app runs on
EXPOSE 5000

# Run the server
CMD ["node", "server.js"]
