# Use a Node.js image
# FROM node:18
FROM node:20.17.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install --save-dev @types/react @types/react-dom
#RUN npm install --force

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 3002

# Run the React app
CMD ["npm", "start"]