# Use a Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
# Using Node Version Manager (nvm)
RUN nvm install 20.17.0
RUN nvm use 20.17.0
RUN npm install -g npm@11.4.2
RUN npm install --force

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Run the React app
CMD ["npm", "start"]